/**
 * Single schema entrypoint consumed by drizzle-kit and by src/lib/db.ts.
 *
 *   schema-auth.ts  GENERATED by better-auth — do not hand-edit.
 *                   Regenerate with: npm run auth:generate-schema
 *   schema-app.ts   Hand-written application tables.
 *
 * Keeping them separate means a better-auth upgrade can regenerate its own
 * tables without ever touching yours, and a diff on schema-auth.ts tells you
 * immediately what a better-auth version changed in the database.
 */
export * from "./schema-auth";
export * from "./schema-app";
