import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/**
 * Router entry — REQUIRED by TanStack Start.
 *
 * The plugin resolves this from `src/router.{ts,tsx}` (its "router entry",
 * marked required). Without it the build fails with:
 *   "Could not resolve entry for router entry: router in .../src"
 *
 * `routeTree.gen.ts` is generated by the router plugin from `src/routes/`.
 * Do not edit it by hand, and do not delete it from version control without
 * regenerating — a fresh `npm run dev` or `npm run build` recreates it.
 */
export function getRouter() {
	return createRouter({
		routeTree,
		// Preload route data + code on hover/touch intent. On a gated site this
		// makes authorised navigation feel instant without prefetching anything
		// for a signed-out visitor.
		defaultPreload: "intent",
		scrollRestoration: true,
	});
}

/**
 * Register the router's types globally so `Link`, `useNavigate` and route hooks
 * are fully type-checked against the actual route tree. This declaration is what
 * turns a typo'd `to="/projcts"` into a compile error.
 */
declare module "@tanstack/react-router" {
	interface Register {
		router: ReturnType<typeof getRouter>;
	}
}
